version: "3.9"
services:
  minio:
    image: minio/minio:RELEASE.2024-03-16T01-01-10Z
    command: server /data --console-address ":9001"
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:minioadmin}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  app:
    build: .
    container_name: lazygallery-app
    depends_on:
      - minio
    ports:
      - "8080:8080"
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER:minioadmin}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD:minioadmin}
      MINIO_REGION: us-east-1
      MINIO_BUCKET_MEDIA: lazygallery-media
      MINIO_BUCKET_THUMBNAILS: lazygallery-thumbnails
      MINIO_BUCKET_ARCHIVES: lazygallery-archives
      SPRING_PROFILES_ACTIVE: docker
    restart: unless-stopped

volumes:
  minio-data:
